# -*- Python -*-

import os
import lit.formats
from lit.llvm import llvm_config

config.name = 'MLIR_TUTORIAL'
config.test_format = lit.formats.ShTest(not llvm_config.use_lit_shell)
config.suffixes = ['.mlir']
config.test_source_root = os.path.dirname(__file__)
config.test_exec_root = os.path.join(config.mlir_tutorial_obj_root, 'tests')

# Load the site-specific configuration generated by CMake.
lit_config.load_config(config, os.path.join(config.test_exec_root, "lit.site.cfg.py"))